### ISSUE TITLE
Document vendor vs file property

### ISSUE THREAD

**Issue by austinpray** [austinpray/asset-builder#25]
https://discourse.roots.io/t/sage-gulp-jshint-trouble-passing-plugins/3181/5

**Comment by merchantguru** [comment]
I faced a # of the mistakes that I've seen others posting about in Discourse regarding adding assets. So, here's a recap of what I'd suggest for this documentation. I'm not sure if this feedback should be here or over at Roots, but since you linked to Discourse here, I'll put it here.

First, in Sage's documentation, they mostly just link to the asset-builder documentation for examples and further help. But in the asset-builder examples, there are no vendor or plugin examples. Also, the asset-builder documentation links back to the Sage documentation as an example - causing a circular reference ;). I understand the asset-builder documentation shouldn't be dependent on Sage examples, but this is causing a disconnect between the two. So, there's not a whole lot of examples or documentation actually when arriving here from Sage.

There is 1 example of vendor / plugin usage [in the spec here](https://github.com/austinpray/asset-builder/blob/96d801d7360d928cf00ddde5b09027fcd735fa10/help/spec.md). A quick win would be to add an assets example: `"assets/scripts/flexslider.min.js"`.

What should be clarified for the `"vendor"` property: it is relative to the theme directory. This is unclear because the `"files"` property uses `"scripts/main.js"` whereas vendor needs to be `"assets/scripts/myvendor.js"`.

Clarify that `"vendor"` is not a generic term. It needs to be `"vendor"`. (I thought it was generic so I begun by using a specific term like `"mycoolvendor"`).

Clarify that by using `"vendor"`, it will not jshint the file. Like me, I saw people wondering how to take out the jshint step from the build process. (I originally added my vendor files to `"files"`).

Clarify: what's the difference between `"files"` and `"vendor"`? Is it simply `"files"` is first-party and will be jshinted whereas `"vendor"` is 3rd-party and will not be jshinted?

Clarify if order matters, whether `"files"` should go before or after `"vendor"`.

Clarify if it matters if vendor scripts are already minified or not.

Clarify when to use `"external": true,`. Is this when the asset is relative to the web root instead of the the theme/project root?

I suggest showing examples that include:
* multiple first-party scripts
* vendor scripts that are concatenated into the final main.js
* vendor scripts outside of main.js, which also requires wp_enqueue_script
* plugin scripts, which also requires dequeue'ing the plugin assets
* `"external": true,` example
* bower scripts (point out these actually go in bower.json)

Here's an example of adding 3rd party vendor scripts and a plugin to the main.js file:
```javascript
    "main.js": {
      "files": [
        "scripts/main.js"
      ],
      "vendor": [
        "assets/scripts/foundry/flexslider.min.js",
        "assets/scripts/foundry/lightbox.min.js",
        "assets/scripts/foundry/masonry.min.js",
        "assets/scripts/foundry/countdown.min.js",
        "assets/scripts/foundry/smooth-scroll.min.js",
        "assets/scripts/foundry/parallax.js",
        "assets/scripts/foundry/foundry-custom.js",
        "../../plugins/example-plugin/js/example-plugin.js"
      ],
      "main": true
    },
```

Here's an example of adding vendor scripts separate from main.js:
https://discourse.roots.io/t/how-to-include-custom-vendor-scripts-on-gulp-production-and-avoid-jshint-errors/3545

**Comment by austinpray** [comment]
@merchantguru this is incredibly helpful. Give me a second and I'll gather my thoughts and make a proper reply. 

In the meantime: I agree that although asset-builder is only loosely coupled with Sage it should still have all of the Sage features documented.

**Comment by merchantguru** [comment]
👍🏽




On Sun, Jun 21, 2015 at 4:32 PM -0700, "Austin Pray" <notifications@github.com<mailto:notifications@github.com>> wrote:


@merchantguru<https://github.com/merchantguru> this is incredibly helpful. Give me a second and I'll gather my thoughts and make a proper reply.

In the meantime: I agree that although asset-builder is only loosely coupled with Sage it should still have all of the Sage features documented.

**Comment by austinpray** [comment]
@merchantguru I've started to incorporate some of your feedback over here: https://github.com/austinpray/asset-builder/pull/43

Feel free to pull request my pull request or make comments

**Comment by jarc100** [comment]
@merchantguru thanks a lot, i spent the last 3 hours try to understanding this. The documentation today August 12, 2015, it's not clear enough yet.

**Comment by austinpray** [comment]
@jarc100 can you share a bit about the trouble you were having in understanding? Even if it's just bullet points or a thought process it would help me out. 

I want to make sure these questions are answered in the documentation.

**Comment by jarc100** [comment]
Forgive me if i have grammar errors, english is not my first language.

As @merchantguru mentioned:
> I'm not sure if this feedback should be here or over at Roots, but since you linked to Discourse here, I'll put it here.

I will give you my feedback as a Sage user by firstly pointing out this, i do not consider myself a developer yet i had design and develop several wordpress sites with my own code all of them using Gulp, Grunt and Sass or Less. This is the first time i try Sage, but i try Roots (when it had that name). So, i'm not an expert nor a newbie in the field.

Why do i said this? 

I started by reading the documentation in [Sage website] (https://roots.io/sage/docs/), when i get to the part of [Theme Development] (https://roots.io/sage/docs/theme-development/) i get a link to the Asset Builder pointing out this: > asset-builder is the manifest file format that’s used to collect all assets and put them in order

I didn't see any example of how to add vendor scripts, personally i think more than few people will find this information very important. It is not clear how to achieve this, you can go to the asset builder and keep searching in the Manifest documentation and the troubleshooting... but still it is not clear on how to achieve the mentioned objetive which is adding third party scripts.

I think there's a lot of room for interpretation. @merchantguru explained a lot better than i, but me as a "regular user" struggled to get things to worked.

Regards.
